# basic options
title: Jens Fischer
author: jeMATHfischer
email: jefischer@posteo.de
description: A collection of work and ideas on dynamic networks and stochastic population systems
github_username: jeMATHfischer

# Build settings
markdown: kramdown
theme:  minima

#kramdown:
#  parse_block_html: true

#navbar
avatar: "{{ site.url }}/images/portrait.jpg"
cv: "{{ site.url }}/assets/Jens_Fischer_CV.pdf"
