# basic options
title: Jens Fischer
author: jeMATHfischer
email: jefischer@posteo.de
description: A collection of work and ideas on dynamic networks and stochastic population systems
github_username: jeMATHfischer

# Build settings
markdown: kramdown
theme:  minima

minima:
	date_format: "%b %-d, %Y"

kramdown:
  parse_block_html: true

#navbar
avatar: "{{ site.url }}/images/portrait.jpg"
cv: "https://github.com/jeMATHfischer/jeMATHfischer.github.io/blob/master/assets/Jens_Fischer_CV.pdf"
