# basic options
title: Jens Fischer
author: jeMATHfischer
email: 
description: A collection of work and ideas on dynamic networks and stochastic population systems
github_username: jeMATHfischer

# Build settings
markdown: kramdown
theme:  minima

kramdown:
  parse_block_html: true

#navbar
avatar: "images/portrait.jpg"
cv: "assets/Jens_Fischer_CV.pdf"
