# basic options
title: N.T.W.R.K.S
author: jeMATHfischer
email: 
description: A collection of work and ideas on dynamic networks and stochastic population systems
github_username: jeMATHfischer

# Build settings
markdown: kramdown
theme: minima

#navbar
avatar: "images/portrait.jpg"
